<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\KooRah.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\Map\tehran.osm.pbf" Link="tehran.osm.pbf" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
